[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:password"
  ]

[http.routers.api]
  rule = "Host(`monitor.territorycounter.org`)"
  entrypoints = ["websecure"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"